# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'zoe_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1080)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.BuConnect = QtWidgets.QPushButton(self.centralwidget)
        self.BuConnect.setGeometry(QtCore.QRect(1750, 870, 91, 31))
        self.BuConnect.setStyleSheet("\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.BuConnect.setObjectName("BuConnect")
        self.TextConnect = QtWidgets.QLabel(self.centralwidget)
        self.TextConnect.setGeometry(QtCore.QRect(1210, 880, 461, 21))
        self.TextConnect.setObjectName("TextConnect")
        self.VisibleEsp = QtWidgets.QSlider(self.centralwidget)
        self.VisibleEsp.setGeometry(QtCore.QRect(1330, 180, 441, 41))
        self.VisibleEsp.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.VisibleEsp.setMouseTracking(True)
        self.VisibleEsp.setTabletTracking(False)
        self.VisibleEsp.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.VisibleEsp.setToolTipDuration(-1)
        self.VisibleEsp.setStyleSheet("QSlider {\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QSlider::groove:horizontal {\n"
"    height: 30px;\n"
"    background: qlineargradient(x1: 0, y1: 0.5, x2: 1, y2: 0.5,\n"
"                                stop: 0 #fc00c6, stop: 0.15 #4B0082,\n"
"                                stop: 0.30 #00ecfc, stop: 0.45 #00FF00,\n"
"                                stop: 0.52 #FFFF00, stop: 0.77 #FF0000,\n"
"                                stop: 1 #FF0000);\n"
"    \n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    width: 5px;\n"
"    margin-top: -4px;\n"
"    margin-bottom: -4px;\n"
"    border-radius: 3px;\n"
"    background: transparent;\n"
"    border: 4px solid #0d0d0c\n"
"}\n"
"\n"
"QSlider::handle:horizontal:hover {\n"
"    background: #BBBBBB;\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal {\n"
"    background: transparent;\n"
"}\n"
"\n"
"QSlider::add-page:horizontal {\n"
"    background: transparent;\n"
"}\n"
"\n"
"")
        self.VisibleEsp.setMinimum(380)
        self.VisibleEsp.setMaximum(780)
        self.VisibleEsp.setPageStep(10)
        self.VisibleEsp.setTracking(True)
        self.VisibleEsp.setOrientation(QtCore.Qt.Horizontal)
        self.VisibleEsp.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.VisibleEsp.setObjectName("VisibleEsp")
        self.wavelength = QtWidgets.QLineEdit(self.centralwidget)
        self.wavelength.setGeometry(QtCore.QRect(1780, 190, 41, 31))
        self.wavelength.setAlignment(QtCore.Qt.AlignCenter)
        self.wavelength.setObjectName("wavelength")
        self.titulo = QtWidgets.QLabel(self.centralwidget)
        self.titulo.setGeometry(QtCore.QRect(1520, 30, 171, 111))
        self.titulo.setObjectName("titulo")
        self.RB_manual = QtWidgets.QRadioButton(self.centralwidget)
        self.RB_manual.setGeometry(QtCore.QRect(1330, 150, 82, 17))
        self.RB_manual.setObjectName("RB_manual")
        self.RB_auto = QtWidgets.QRadioButton(self.centralwidget)
        self.RB_auto.setGeometry(QtCore.QRect(1330, 230, 82, 17))
        self.RB_auto.setObjectName("RB_auto")
        self.RB_white = QtWidgets.QRadioButton(self.centralwidget)
        self.RB_white.setGeometry(QtCore.QRect(1330, 260, 82, 17))
        self.RB_white.setObjectName("RB_white")
        self.img_microscopy = QtWidgets.QLabel(self.centralwidget)
        self.img_microscopy.setGeometry(QtCore.QRect(1430, 20, 71, 111))
        self.img_microscopy.setText("")
        self.img_microscopy.setPixmap(QtGui.QPixmap("microscopio.png"))
        self.img_microscopy.setScaledContents(True)
        self.img_microscopy.setObjectName("img_microscopy")
        self.tablero = QtWidgets.QLabel(self.centralwidget)
        self.tablero.setGeometry(QtCore.QRect(10, 10, 1300, 850))
        self.tablero.setStyleSheet("background-color: rgba(255, 0, 0, 10);")
        self.tablero.setText("")
        self.tablero.setObjectName("tablero")
        self.tablero_2 = QtWidgets.QLabel(self.centralwidget)
        self.tablero_2.setGeometry(QtCore.QRect(10, 10, 1300, 850))
        self.tablero_2.setStyleSheet("background-color: rgba(85, 170, 0, 10);")
        self.tablero_2.setText("")
        self.tablero_2.setObjectName("tablero_2")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 860, 295, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pbSave = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pbSave.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";")
        self.pbSave.setObjectName("pbSave")
        self.horizontalLayout.addWidget(self.pbSave)
        self.pbDot = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pbDot.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";\n"
"")
        self.pbDot.setObjectName("pbDot")
        self.horizontalLayout.addWidget(self.pbDot)
        self.pbTrash = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pbTrash.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";")
        self.pbTrash.setObjectName("pbTrash")
        self.horizontalLayout.addWidget(self.pbTrash)
        self.tablero_2.raise_()
        self.BuConnect.raise_()
        self.TextConnect.raise_()
        self.VisibleEsp.raise_()
        self.wavelength.raise_()
        self.titulo.raise_()
        self.RB_manual.raise_()
        self.RB_auto.raise_()
        self.RB_white.raise_()
        self.img_microscopy.raise_()
        self.tablero.raise_()
        self.horizontalLayoutWidget.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1920, 26))
        self.menuBar.setObjectName("menuBar")
        self.menuArchivo = QtWidgets.QMenu(self.menuBar)
        self.menuArchivo.setObjectName("menuArchivo")
        self.menuColor = QtWidgets.QMenu(self.menuBar)
        self.menuColor.setObjectName("menuColor")
        self.menuTama_o = QtWidgets.QMenu(self.menuBar)
        self.menuTama_o.setObjectName("menuTama_o")
        self.menuCamara = QtWidgets.QMenu(self.menuBar)
        self.menuCamara.setObjectName("menuCamara")
        MainWindow.setMenuBar(self.menuBar)
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actiondos = QtWidgets.QAction(MainWindow)
        self.actiondos.setObjectName("actiondos")
        self.actionClear = QtWidgets.QAction(MainWindow)
        self.actionClear.setObjectName("actionClear")
        self.action3px = QtWidgets.QAction(MainWindow)
        self.action3px.setObjectName("action3px")
        self.action5px = QtWidgets.QAction(MainWindow)
        self.action5px.setObjectName("action5px")
        self.action7px = QtWidgets.QAction(MainWindow)
        self.action7px.setObjectName("action7px")
        self.action9px = QtWidgets.QAction(MainWindow)
        self.action9px.setObjectName("action9px")
        self.actionNegro = QtWidgets.QAction(MainWindow)
        self.actionNegro.setObjectName("actionNegro")
        self.actionRojo = QtWidgets.QAction(MainWindow)
        self.actionRojo.setObjectName("actionRojo")
        self.actionAzul = QtWidgets.QAction(MainWindow)
        self.actionAzul.setObjectName("actionAzul")
        self.actionAmarillo = QtWidgets.QAction(MainWindow)
        self.actionAmarillo.setObjectName("actionAmarillo")
        self.actionVerde = QtWidgets.QAction(MainWindow)
        self.actionVerde.setObjectName("actionVerde")
        self.actionInstrucciones = QtWidgets.QAction(MainWindow)
        self.actionInstrucciones.setObjectName("actionInstrucciones")
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionRojo_2 = QtWidgets.QAction(MainWindow)
        self.actionRojo_2.setObjectName("actionRojo_2")
        self.actionVerde_2 = QtWidgets.QAction(MainWindow)
        self.actionVerde_2.setObjectName("actionVerde_2")
        self.actionAzul_2 = QtWidgets.QAction(MainWindow)
        self.actionAzul_2.setObjectName("actionAzul_2")
        self.actionAmarrillo = QtWidgets.QAction(MainWindow)
        self.actionAmarrillo.setObjectName("actionAmarrillo")
        self.actionNegro_2 = QtWidgets.QAction(MainWindow)
        self.actionNegro_2.setObjectName("actionNegro_2")
        self.actionBlanco = QtWidgets.QAction(MainWindow)
        self.actionBlanco.setObjectName("actionBlanco")
        self.action1_Px = QtWidgets.QAction(MainWindow)
        self.action1_Px.setObjectName("action1_Px")
        self.action3_Px = QtWidgets.QAction(MainWindow)
        self.action3_Px.setObjectName("action3_Px")
        self.action5_Px = QtWidgets.QAction(MainWindow)
        self.action5_Px.setObjectName("action5_Px")
        self.action7_Px = QtWidgets.QAction(MainWindow)
        self.action7_Px.setObjectName("action7_Px")
        self.action9_Px = QtWidgets.QAction(MainWindow)
        self.action9_Px.setObjectName("action9_Px")
        self.menuArchivo.addAction(self.actionInstrucciones)
        self.menuArchivo.addAction(self.actionClose)
        self.menuColor.addAction(self.actionRojo_2)
        self.menuColor.addAction(self.actionVerde_2)
        self.menuColor.addAction(self.actionAzul_2)
        self.menuColor.addAction(self.actionAmarrillo)
        self.menuColor.addAction(self.actionNegro_2)
        self.menuColor.addAction(self.actionBlanco)
        self.menuTama_o.addAction(self.action1_Px)
        self.menuTama_o.addAction(self.action3_Px)
        self.menuTama_o.addAction(self.action5_Px)
        self.menuTama_o.addAction(self.action7_Px)
        self.menuTama_o.addAction(self.action9_Px)
        self.menuBar.addAction(self.menuArchivo.menuAction())
        self.menuBar.addAction(self.menuColor.menuAction())
        self.menuBar.addAction(self.menuTama_o.menuAction())
        self.menuBar.addAction(self.menuCamara.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ZOE microscopy"))
        self.BuConnect.setText(_translate("MainWindow", "Conectar"))
        self.TextConnect.setText(_translate("MainWindow", "<html><head/><body><p>conexión</p></body></html>"))
        self.wavelength.setText(_translate("MainWindow", "380"))
        self.titulo.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:48pt; font-weight:600;\">ZOE</span></p></body></html>"))
        self.RB_manual.setText(_translate("MainWindow", "Manual"))
        self.RB_auto.setText(_translate("MainWindow", "Automático"))
        self.RB_white.setText(_translate("MainWindow", "Luz blanca"))
        self.pbSave.setText(_translate("MainWindow", "💾"))
        self.pbDot.setText(_translate("MainWindow", "✍️"))
        self.pbTrash.setText(_translate("MainWindow", "🗑️"))
        self.menuArchivo.setTitle(_translate("MainWindow", "ZOE"))
        self.menuColor.setTitle(_translate("MainWindow", "Color "))
        self.menuTama_o.setTitle(_translate("MainWindow", "Tamaño"))
        self.menuCamara.setTitle(_translate("MainWindow", "Camara"))
        self.actionSave.setText(_translate("MainWindow", "Guardar"))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actiondos.setText(_translate("MainWindow", "dos"))
        self.actionClear.setText(_translate("MainWindow", "Limpiar"))
        self.actionClear.setShortcut(_translate("MainWindow", "Ctrl+L"))
        self.action3px.setText(_translate("MainWindow", "3px"))
        self.action5px.setText(_translate("MainWindow", "5px"))
        self.action7px.setText(_translate("MainWindow", "7px"))
        self.action9px.setText(_translate("MainWindow", "9px"))
        self.actionNegro.setText(_translate("MainWindow", "Negro"))
        self.actionRojo.setText(_translate("MainWindow", "Rojo"))
        self.actionAzul.setText(_translate("MainWindow", "Azul"))
        self.actionAmarillo.setText(_translate("MainWindow", "Amarillo"))
        self.actionVerde.setText(_translate("MainWindow", "Verde"))
        self.actionInstrucciones.setText(_translate("MainWindow", "Instrucciones "))
        self.actionClose.setText(_translate("MainWindow", "Cerrar"))
        self.actionRojo_2.setText(_translate("MainWindow", "Rojo"))
        self.actionVerde_2.setText(_translate("MainWindow", "Verde"))
        self.actionAzul_2.setText(_translate("MainWindow", "Azul"))
        self.actionAmarrillo.setText(_translate("MainWindow", "Amarrillo"))
        self.actionNegro_2.setText(_translate("MainWindow", "Negro"))
        self.actionBlanco.setText(_translate("MainWindow", "Blanco "))
        self.action1_Px.setText(_translate("MainWindow", "1 Px"))
        self.action3_Px.setText(_translate("MainWindow", "3 Px"))
        self.action5_Px.setText(_translate("MainWindow", "5 Px"))
        self.action7_Px.setText(_translate("MainWindow", "7 Px"))
        self.action9_Px.setText(_translate("MainWindow", "9 Px"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
